export const topGenres = [
  "Bollywood / Filmi / Hindi",
  "English/Western",
  "Punjabi",
  "Ghazal",
  "Sufi",
  "Qawwali",
  "Rock",
  "Pop",
  "Jazz",
  "Electronic",
  "Retro / Old (Bollywood / Hindi)",
  "Orchestra (Bollywood Retro)",
  "Symphony",
  "Karaoke",
  "English Retro",
  "Indie (India)",
  "Indie Pop (India)",
  "Indie",
  "Indie Pop",
  "Mayra / Bhaat",
  "Vedic / Musical Pheras",
  "Soul",
  "English Blues",
  "Blues",
  "Classical",
  "Punjabi Folk",
  "Semi Classical",
  "Metal",
  "Soft Rock",
  "Alternative Rock",
  "Rajasthani Folk",
  "Bhojpuri",
  "Bengali",
  "Assame",
  "Dandiya/Garba",
  "Marathi",
  "Punjabi Tappe",
  "Bhangara",
  "Ravindra Sangeet",
  "Odissi / Odia / Odissa",
  "Devotional/Bhajan",
  "Hip Hop",
  "Tamil",
  "Malayalam",
  "Telugu",
  "Gujarati",
  "Sindhi",
  "Carnatic Music",
  "Maithili",
  "R&B",
  "Country",
  "Reggage",
  "Punk",
  "Funk",
  "Rap",
  "Indian Filmi Pop",
];
