const instrumentOptions = [
  "Accordina",
  "Accordion",
  "Algozey",
  "Alphorn",
  "Alto Clarinet",
  "Alto Flute",
  "Alto Saxophone",
  "Anglo Concertina",
  "Antara",
  "Arghul",
  "Bagpipe",
  "Bandoneón",
  "Bansuri",
  "Baritone Horn",
  "Baritone Saxophone",
  "Baroque Rackett",
  "Baroque Trumpet",
  "Barrel Organ",
  "Bass Clarinet",
  "Bass Flute",
  "Bass Harmonica",
  "Bass Oboe",
  "Bass Recorder",
  "Bass Saxophone",
  "Bass Trombone",
  "Bass Trumpet",
  "Basset Clarinet",
  "Basset Horn",
  "Bassoon",
  "Bawu",
  "Bayan",
  "Bazooka",
  "Bellowed Reed",
  "Biniou",
  "Birbynė",
  "Birch Lur",
  "Boatswain's Pipe",
  "Bombarde",
  "Brass",
  "Bronze Lur",
  "Bugle",
  "Buisine",
  "Button Accordion",
  "Cabrette",
  "Calliope",
  "Cembalet",
  "Chalumeau",
  "Chamber Organ",
  "Charumera",
  "Chirimía",
  "Chromatic Button Accordion",
  "Chromatic Harmonica",
  "Cimbasso",
  "Cimpoi",
  "Clarinet",
  "Claviola",
  "Concertina",
  "Conch",
  "Contrabass Clarinet",
  "Contrabass Flute",
  "Contrabass Recorder",
  "Contrabass Saxophone",
  "Contrabassoon",
  "Cor Anglais",
  "Cornamuse",
  "Cornemuse Du Centre",
  "Cornet",
  "Cornett",
  "Crumhorn",
  "Daegeum",
  "Danso",
  "Diatonic Button Accordion",
  "Didgeridoo",
  "đing Buốt",
  "đing Năm",
  "Ding Tac Ta",
  "Dizi",
  "Double Reed",
  "Duck Call",
  "Dūdmaišis",
  "Duduk",
  "Dudy",
  "Dudy Podhalanskie",
  "Dudy Wielkopolskie",
  "Dulcian",
  "Dulzaina",
  "E-flat Clarinet",
  "End-blown Flute",
  "English Concertina",
  "English Flageolet",
  "Euphonium",
  "Fife",
  "Fipple Flute",
  "Fiscorn",
  "Flabiol",
  "Flageolet",
  "Flugelhorn",
  "Flumpet",
  "Flute",
  "Flûte D'amour",
  "Flutina",
  "Footbass",
  "Free Reed",
  "French Horn",
  "Fujara",
  "Gaida",
  "Gaita Asturiana",
  "Gaita De Boto",
  "Gaita Gallega",
  "Gaita Sanabresa",
  "Gajdy",
  "Garklein Recorder",
  "Garmon",
  "Gemshorn",
  "German Concertina",
  "Gralla",
  "Great Bass Recorder / C-bass Recorder",
  "Great Highland Bagpipe",
  "Guan",
  "Härjedalspipa",
  "Harmonica",
  "Harmonium",
  "Heckelphone",
  "Helicon",
  "Hichiriki",
  "Hmông Flute",
  "Horn",
  "Hotchiku",
  "Hue Puruhau",
  "Hulusi",
  "Hümmelchen",
  "Irish Flute",
  "Jug",
  "K'lông Pút",
  "Kagurabue",
  "Kaval",
  "Kèn Bầu",
  "Kèn Lá",
  "Keyed Brass Instruments",
  "Khèn Mèo",
  "Khene",
  "Khlui",
  "Ki Pah",
  "Kōauau",
  "Kōauau Ponga Ihu",
  "Kortholt",
  "Launeddas",
  "Limbe",
  "Low Whistle",
  "Magyar Duda",
  "Mashak",
  "Matstsyanka",
  "Mellophone",
  "Melodica",
  "Melophone",
  "Mezwed",
  "Mijwiz",
  "Mirliton",
  "Mouth Organ",
  "Musette De Cour",
  "Nabal",
  "Nadaswaram",
  "Nagak",
  "Nai",
  "Natural Brass Instruments",
  "Natural Horn",
  "Natural Trumpet",
  "Ney",
  "Neyanban",
  "Nguru",
  "Nohkan",
  "Northumbrian Pipes",
  "Nose Flute",
  "Nose Whistle",
  "Oboe",
  "Oboe D'amore",
  "Oboe Da Caccia",
  "Ocarina",
  "Olifant",
  "Ophicleide",
  "Organ",
  "Pan Flute",
  "Pang Gu Ly Hu Hmông",
  "Parkapzuk",
  "Pedal Accordion",
  "Pi Nai",
  "Pí Thiu",
  "Piano Accordion",
  "Piccolo",
  "Piccolo Oboe",
  "Piccolo Trumpet",
  "Piffero",
  "Pipe Organ",
  "Piri",
  "Piva",
  "Pocket Trumpet",
  "Poi Āwhiowhio",
  "Porotiti",
  "Portative",
  "Pōrutu",
  "Post Horn",
  "Practice Chanter",
  "Pūkaea",
  "Pūmotomoto",
  "Pūpakapaka",
  "Pūtātara",
  "Pūtōrino",
  "Quadruple Reed",
  "Quena",
  "Rauschpfeife",
  "Reclam De Xeremies",
  "Recorder",
  "Reed Organ",
  "Reeds",
  "Regal",
  "Rehu",
  "Renaissance Rackett",
  "Rondador",
  "Ryuteki",
  "Sac De Gemecs",
  "Sackbut",
  "Säckpipa",
  "Saduk",
  "Saluang",
  "Samba Whistle",
  "Sáo Meò",
  "Sáo Trúc",
  "Sarrusophone",
  "Saxophone",
  "Schwyzerörgeli",
  "Scottish Smallpipes",
  "Serpent",
  "Shakuhachi",
  "Shawm",
  "Shehnai",
  "Sheng",
  "Shinobue",
  "Sho",
  "Shofar",
  "Shruti Box",
  "Siku",
  "Single Reed",
  "Slide Brass Instruments",
  "Slide Whistle",
  "Somu Dūdas",
  "Sopilka",
  "Sopranino Recorder",
  "Sopranino Saxophone",
  "Soprano Clarinet",
  "Soprano Flute",
  "Soprano Recorder",
  "Soprano Saxophone",
  "Sordellina",
  "Sousaphone",
  "Spilåpipa",
  "Subcontrabass Recorder",
  "Suling",
  "Suona",
  "Syrinx",
  "Taepyeongso",
  "Taragot",
  "Tarota",
  "Tenor Horn / Alto Horn",
  "Tenor Recorder",
  "Tenor Saxophone",
  "Tenor Trombone",
  "Tenora",
  "Theatre Organ",
  "Three-hole Pipe",
  "Tible",
  "Tiêu",
  "Tin Whistle",
  "Tonette",
  "Torupill",
  "Tràm Plè",
  "Trắng Jâu",
  "Trắng Lu",
  "Transverse Flute",
  "Treble Flute",
  "Treble Recorder / Alto Recorder",
  "Trikiti",
  "Trombone",
  "Trumpet",
  "Tsampouna",
  "Tuba",
  "Tubax",
  "Tulum",
  "Tungso",
  "Txistu",
  "Uilleann Pipes",
  "Valve Trombone",
  "Valved Brass Instruments",
  "Venu",
  "Vessel Flute",
  "Veuze",
  "Vibrandoneon",
  "Vuvuzela",
  "Wagner Tuba",
  "Whistle",
  "Wiener Horn",
  "Willow Flute",
  "Wind Instruments",
  "Woodwind",
  "Wot",
  "Xaphoon",
  "Xeremies",
  "Xiao",
  "Xun",
  "Zampogna",
  "żaqq",
  "Zhaleika",
  "Zurna",
  "12 String Guitar",
  "17-string Bass Koto",
  "Acoustic Bass Guitar",
  "Acoustic Fretless Guitar",
  "Acoustic Guitar",
  "Aeolian Harp",
  "Ajaeng",
  "Akkordolia",
  "Alto Viol",
  "Alto Violin",
  "Appalachian Dulcimer",
  "Archlute",
  "Archtop Guitar",
  "Arpeggione",
  "Autoharp",
  "Bağlama",
  "Baglamas",
  "Bajo Sexto",
  "Balalaika",
  "Bandora",
  "Bandura",
  "Bandurria",
  "Banhu",
  "Banjitar",
  "Banjo",
  "Banjo-ukulele",
  "Banjolin",
  "Barbat",
  "Baritone Guitar",
  "Baroque Guitar",
  "Baryton",
  "Bass Guitar",
  "Bass Viol",
  "Bass Violin",
  "Berda",
  "Berimbau",
  "Bhapang",
  "Bin-sitar",
  "Bisernica",
  "Biwa",
  "Blaster Beam",
  "Bolon",
  "Bouzar / Gouzouki",
  "Bouzouki",
  "Bowed Lute",
  "Bowed Lyre",
  "Bowed Piano",
  "Bowed Psaltery",
  "Bowed String Instruments",
  "Brač",
  "Bugarija",
  "Bulbul Tarang",
  "Buzuq",
  "Cavaquinho",
  "Cello",
  "čelo",
  "Chakhe",
  "Chanzy",
  "Chapman Stick",
  "Charango",
  "Chikuzen Biwa",
  "Chitarra Battente",
  "Chitra Veena",
  "Chuurqin",
  "Cimbalom",
  "Citole",
  "Cittern",
  "Cizhonghu",
  "Classical Guitar",
  "Classical Kemençe",
  "Clavichord",
  "Clavinet",
  "Cò Ke",
  "Concert Harp",
  "Craviola",
  "Cretan Lyra",
  "Crwth",
  "Cuatro",
  "Cümbüş",
  "đàn Bầu",
  "đàn Nguyệt",
  "đàn Nhị",
  "đàn Tam",
  "đàn Tam Thập Lục",
  "đàn Tranh",
  "đàn Tứ",
  "đàn Tứ Dây",
  "đàn Tỳ Bà",
  "Daruan",
  "Diddley Bow",
  "Dilruba",
  "Diyingehu",
  "Djoza",
  "Dolceola",
  "Dombra",
  "Domra",
  "Donso Ngɔni",
  "Doshpuluur",
  "Double Bass",
  "Dramyin",
  "Dulce Melos",
  "Dutar",
  "Duxianqin",
  "Electric Bass Guitar",
  "Electric Cello",
  "Electric Fretless Guitar",
  "Electric Grand Piano",
  "Electric Guitar",
  "Electric Harp",
  "Electric Lap Steel Guitar",
  "Electric Sitar",
  "Electric Upright Bass",
  "Electric Viola",
  "Electric Violin",
  "Erhu",
  "Esraj",
  "Five-string Banjo",
  "Flamenco Guitar",
  "Folk Harp",
  "Fortepiano",
  "Four-string Banjo",
  "Fretless Bass",
  "Gadulka",
  "Gaohu",
  "Gayageum",
  "Gehu",
  "Geomungo",
  "German Harp",
  "Ghaychak",
  "Ghijak",
  "ģīga",
  "Gittern",
  "Gopichant",
  "Grand Piano",
  "Gravikord",
  "Gudok",
  "Guitalele",
  "Guitar",
  "Guitarrón Chileno",
  "Guitarrón Mexicano",
  "Gumbri",
  "Guqin",
  "Gusli",
  "Guzheng",
  "Haegeum",
  "Hammered Dulcimer",
  "Hardingfele",
  "Harp",
  "Harp Guitar",
  "Harpejji",
  "Harpsichord",
  "Hawaiian Guitar",
  "Heike Biwa",
  "Hummel",
  "Hurdy Gurdy",
  "Igil",
  "Indonesian Rebab",
  "Irish Bouzouki",
  "Irish Harp / Clàrsach",
  "Jantar",
  "Jeli Ngɔni",
  "Jing'erhu",
  "Jinghu",
  "Jouhikko",
  "Kacapi",
  "Kacapi Indung",
  "Kacapi Rincik",
  "Kacapi Siter",
  "Kachva Sitar",
  "Kamale Ngɔni",
  "Kamancheh",
  "Kanklės",
  "Kannel",
  "Kantele",
  "Kanun",
  "Kemençe Of The Black Sea",
  "Kemenche",
  "Keyed Box Zither",
  "Khim",
  "Kinnor",
  "Kithara",
  "Kokle",
  "Kokyu",
  "Komuz",
  "Kora",
  "Koto",
  "Krar",
  "Langeleik",
  "Laouto",
  "Lap Harp",
  "Lap Steel Guitar",
  "Laúd",
  "Lautenwerck",
  "Lavta",
  "Lira Da Braccio",
  "Lirone",
  "Liuqin",
  "Lute",
  "Luthéal",
  "Lyra Viol",
  "Lyre",
  "Mandocello",
  "Mandoguitar",
  "Mandola",
  "Mandolin",
  "Mandolute",
  "Mandora / Gallichon",
  "Marxophone",
  "Mexican Vihuela",
  "Minipiano",
  "Morin Khuur",
  "Musical Bow",
  "Ngɔni",
  "Njarka",
  "Nyatiti",
  "Nyckelharpa",
  "Octave Mandolin",
  "Octavilla",
  "Octavina",
  "Octobass",
  "Oktawka",
  "Orpharion",
  "Orphica",
  "Oud",
  "Oval Spinet",
  "Paraguayan Harp",
  "Pardessus De Viole",
  "Pedal Piano",
  "Pedal Steel Guitar",
  "Piano",
  "Piano Spinet",
  "Pipa",
  "Plucked String Instruments",
  "Pluriarc",
  "Portuguese Guitar",
  "Prepared Piano",
  "Psaltery",
  "Ravanahatha",
  "Rebab",
  "Rebec",
  "Resonator Guitar",
  "Ronroco",
  "Ruan",
  "Rubab",
  "Rudra Veena",
  "Samica",
  "Sanshin",
  "Santoor",
  "Santur",
  "Sanxian",
  "Sarangi",
  "Saraswati Veena",
  "šargija",
  "Sarod",
  "Sasando",
  "Satsuma Biwa",
  "Saw Duang",
  "Saw Sam Sai",
  "Saw U",
  "Saz",
  "Seni Rebab",
  "Setar",
  "Shamisen",
  "Shichepshin",
  "Shudraga",
  "Sitar",
  "Slide Guitar",
  "Soprano Violin",
  "Spike-fiddle",
  "Spinet",
  "Spinettone",
  "Steel Guitar",
  "Steel-string Acoustic Guitar",
  "Stick Zither",
  "Strings",
  "Stroh Violin",
  "Struck String Instruments",
  "Suka",
  "Surbahar",
  "Sursingar",
  "Swarmandal",
  "Table Steel Guitar",
  "Tack Piano",
  "Taishogoto",
  "Talharpa",
  "Tambura",
  "Tanbur",
  "Tangent Piano",
  "Tanpura",
  "Tar",
  "Te Kū",
  "Tenor Banjo",
  "Tenor Guitar",
  "Tenor Viol",
  "Tenor Violin",
  "Theorbo",
  "Tiple",
  "Tololoche",
  "Tonkori",
  "Topshuur",
  "Toy Piano",
  "Treble Viol",
  "Treble Violin",
  "Tres",
  "Tritantri Veena",
  "Tromba Marina",
  "Tube Zither",
  "Tumbi",
  "Tzoura",
  "Ukeke",
  "Ukulele",
  "Upright Piano",
  "ütőgardon",
  "Valiha",
  "Vichitra Veena",
  "Vielle",
  "Vietnamese Guitar",
  "Vihuela",
  "Viola",
  "Viola Caipira",
  "Viola D'amore",
  "Viola Da Gamba",
  "Viola Organista",
  "Violin",
  "Violino Piccolo",
  "Viololyra",
  "Violoncello Piccolo",
  "Violone",
  "Violotta",
  "Virginal",
  "Walaycho",
  "Warr Guitar",
  "Washtub Bass",
  "Wire-strung Harp",
  "Xalam",
  "Yangqin",
  "Yatga",
  "Yaylı Tanbur",
  "Yehu",
  "Yoochin",
  "Yueqin",
  "Zhonghu",
  "Zhongruan",
  "Zhuihu",
  "Zither",
  "Afoxé",
  "Agogô",
  "Akete",
  "Alfaia",
  "Amadinda",
  "Aman Khuur",
  "Angklung",
  "Ankle Rattlers",
  "Anvil",
  "Arrabel",
  "Ashiko",
  "Atabaque",
  "Atarigane",
  "Baandu",
  "Balafon",
  "Bangu",
  "Barrel Drum",
  "Bass Drum",
  "Batá Drum",
  "Bedug",
  "Bell",
  "Bell Plate",
  "Bell Tree",
  "Bendir",
  "Bicycle Bell",
  "Bin-sasara",
  "Bodhrán",
  "Body Percussion",
  "Bombo Legüero",
  "Bonang",
  "Bonang Barung",
  "Bonang Panembung",
  "Bonang Panerus",
  "Bones",
  "Bongos",
  "Boobam",
  "Boomwhacker",
  "Brushes",
  "Buk",
  "Cabasa",
  "Caixa",
  "Cajón",
  "Calabash",
  "Calung",
  "Carillon",
  "Castanets",
  "Caxixi",
  "Celesta",
  "çevgen",
  "Chacha",
  "Chande",
  "Chap",
  "Chau Gong",
  "Chime Bar",
  "Chimes",
  "Ching",
  "Clapper",
  "Clapstick",
  "Claves",
  "Concussion Idiophone",
  "Congas",
  "Cowbell",
  "Cristal Baschet",
  "Crotales",
  "Cuíca",
  "Cylindrical Drum",
  "Cymbal",
  "Daf",
  "Daire",
  "Daluo",
  "Darbuka",
  "Davul",
  "Dhol",
  "Dholak",
  "Djembe",
  "Dohol",
  "Doyra",
  "Drums (Drum Set)",
  "Duggi",
  "Dulcitone",
  "Dunun",
  "Electronic Drum Set",
  "Finger Cymbals",
  "Finger Snaps",
  "Foot Stomps",
  "Frame Drum",
  "Friction Drum",
  "Friction Idiophone",
  "Frottoir",
  "Fundeh",
  "Gambang",
  "Gankogui",
  "Ganzá",
  "Garifuna Drum",
  "Gendèr Barung",
  "Gendèr Panerus",
  "Gendèr Wayang",
  "Ghatam",
  "Glass Harmonica",
  "Glass Harp",
  "Glockenspiel",
  "Goblet Drum",
  "Gong",
  "Gong Bass Drum",
  "Gong-chime",
  "Gramorimba",
  "Güira",
  "Güiro",
  "Handbell",
  "Handclaps",
  "Handpan",
  "Hi-hat",
  "Hourglass Drum",
  "Hue Puruwai",
  "Hyoshigi",
  "Idiophone",
  "Janggu",
  "Jegogan",
  "Jing",
  "Jublag",
  "Junjung",
  "Kanjira",
  "Kantilan",
  "Kartal",
  "Kecer",
  "Kemanak",
  "Kempli",
  "Kempul",
  "Kempyang",
  "Kendang",
  "Kendang Lanang",
  "Kendang Wadon",
  "Kendhang Batangan",
  "Kendhang Gendhing",
  "Kendhang Indung",
  "Kendhang Ketipung",
  "Kendhang Kulanter",
  "Kendhang Wayangan",
  "Kenong",
  "Kepyak",
  "Kethuk",
  "Kettle Drum",
  "Khong Wong",
  "Khong Wong Lek",
  "Khong Wong Yai",
  "Khulsan Khuur",
  "Kkwaenggwari",
  "Klong Khaek",
  "Klong Song Na",
  "Klong That",
  "Klong Yao",
  "Kös",
  "Kotsuzumi",
  "Krakebs",
  "Krap Khū",
  "Krap Phuang",
  "Krap Sēphā",
  "Kudüm",
  "Lamellaphone",
  "Lithophone",
  "Madal",
  "Maddale",
  "Maracas",
  "Marimba",
  "Marímbula",
  "Mark Tree",
  "Mbira",
  "Membranophone",
  "Monkey Stick",
  "Morsing",
  "Mouth Harp",
  "Mridangam",
  "Mukkuri",
  "Musical Box",
  "Nagadou-daiko",
  "Naobo",
  "Ocean Drum",
  "Octoban",
  "ōtsuzumi",
  "Pahū",
  "Pahū Pounamu",
  "Paiban",
  "Pakhawaj",
  "Pākuru",
  "Pātē",
  "Pemade",
  "Percussion",
  "Percussion Idiophone",
  "Phách",
  "Pkhachich",
  "Plucked Idiophone",
  "Poi",
  "Primero",
  "Qilaut",
  "Quijada",
  "Quinto",
  "Rainstick",
  "Rammana",
  "Ranat Ek",
  "Ranat Kaeo",
  "Ranat Thum",
  "Ratchet",
  "Reco-reco",
  "Repeater",
  "Repinique",
  "Reyong",
  "Rhodes Piano",
  "Rhythm Sticks",
  "Riq",
  "Rōria",
  "Rototom",
  "Sabar",
  "Saron Barung",
  "Saron Demung",
  "Saron Family",
  "Saron Panerus",
  "Saron Peking",
  "Saron Wayang",
  "Scraped Idiophone",
  "Segunda",
  "Sênh Tiền",
  "Shaken Idiophone",
  "Shakers",
  "Shekere",
  "Shime-daiko",
  "Singing Bowl",
  "Sistrum",
  "Slapstick",
  "Slenthem",
  "Slentho",
  "Slit Drum",
  "Snare Drum",
  "Song Loan",
  "Spoons",
  "Steelpan",
  "Struck Idiophone",
  "Surdo",
  "T'rưng",
  "Tabla",
  "Tabor",
  "Taiko",
  "Talking Drum",
  "Tamborim",
  "Tambourine",
  "Tanbou Ka",
  "Tap Dance",
  "Taphon",
  "Tar",
  "Tef",
  "Temple Blocks",
  "Temür Khuur",
  "Thavil",
  "The Great Stalacpipe Organ",
  "Thon",
  "Ti Bwa",
  "Tibetan Water Drum",
  "Timbales",
  "Timpani",
  "Tinya",
  "Tōkere",
  "Tom-tom",
  "Triangle",
  "Trống Bông",
  "Tubular Bells",
  "Tubulum",
  "Tumutumu",
  "Txalaparta",
  "Typewriter",
  "Udu",
  "Ugal",
  "Vibraphone",
  "Vibraslap",
  "Washboard",
  "Waterphone",
  "Wind Chime",
  "Wood Block",
  "Wooden Fish",
  "Wurlitzer Electric Piano",
  "Xiaoluo",
  "Xylophone",
  "Xylorimba",
  "Yonggo",
  "Yu",
  "Zabumba",
  "żafżafa",
  "Zarb",
  "Zill",
  "Analog Synthesizer",
  "Bass Pedals",
  "Bass Synthesizer",
  "Chamberlin",
  "Clavioline",
  "Continuum",
  "Denis D'or",
  "Disk Drive",
  "Drum Machine",
  "Dubreq Stylophone",
  "Ebow",
  "Electronic Instruments",
  "Electronic Organ",
  "Elektronium",
  "Ewi",
  "Farfisa",
  "Floppy Disk Drive",
  "Game Console Sound Chip",
  "Guitar Synthesizer",
  "Guitaret",
  "Guitorgan",
  "Hammond Organ",
  "Hard Disk Drive",
  "Keyboard",
  "Keyboard Bass",
  "Keytar",
  "Laser Harp",
  "Lyricon",
  "Marimba Lumina",
  "Mellotron",
  "Minimoog",
  "Moog",
  "Omnichord",
  "Ondes Martenot",
  "Ondioline",
  "Otamatone",
  "Pianet",
  "Reactable",
  "Sampler",
  "String Synthesizer",
  "Synclavier",
  "Synthesizer",
  "Telharmonium",
  "Theremin",
  "Trautonium",
  "Tubon",
  "Vocoder",
  "Voice Synthesizer",
  "Wavedrum",
  "Wind Synthesizer",
  "Bass",
  "Bullroarer",
  "Effects",
  "Electric Piano",
  "Gizmo",
  "Hydraulophone",
  "Kazoo",
  "Lasso D'amore",
  "Musical Saw",
  "Other Instruments",
  "Pūrerehua",
  "Suikinkutsu",
  "Talkbox",
  "Tape",
  "Turntable",
  "Vacuum Cleaner",
  "żummara",
  "Chirimía And Drum",
  "Cobla",
  "Cobla De Tres Quartans",
  "Gamelan",
  "Guban",
  "Piano Duo",
  "Piano Four Hands",
  "Piano Quartet",
  "Piano Trio",
  "Pierrot Ensemble",
  "Pipe And Tabor",
  "Saxophone Quartet",
  "Serbo-croatian Tamburica Orchestra",
  "String Quartet",
  "String Quintet",
  "String Trio",
  "Taonga Pūoro",
  "Traditional Basque Ensemble",
  "Viol Consort",
  "Violin Octet",
  "Bağlama (Saz) Family",
  "Baltic Psalteries",
  "Bīn",
  "Concert Flute",
  "Fiddle",
  "Gendèr",
  "Guitar Family",
  "Huqin",
  "Krap",
  "Lute Family",
  "Metallophone",
  "Pi",
  "Trumpet Family",
  "Veena",
  "Viol Family",
  "Violin Family",
  "Claviorganum",
];

export default instrumentOptions;
